### PR TITLE
Apply Yu Gothic UI

### PR DESCRIPTION
**Pull request by hope366**
I applied Yu Gothic UI to almost all items.
I excluded it because it doesn't work for the title and body of the dialog box and the html tag is displayed as it is.
Also, for the lower toolbar, the font of Yu Gothic UI is displayed, but it has not been applied because there was a problem that the display space was extended. 
If you can make the lower toolbar Yu Gothic UI, it will look better, so it would be helpful if you could make changes to enable Yu Gothic UI like the upper menu.

### CODE REVIEW

**Comment by yzyray** [comment]
There is another way to change all component's font to a certain one,does this screenshot looks right?
image

**Comment by hope366** [comment]
Yes, it looks right. However, katakana doesn't look very good compared to the Yu Gothic UI.

**Comment by yzyray** [comment]
Does this looks like using Yu Gothic UI?
image
image

**Comment by hope366** [comment]
Paste the image of Yu Gothic UI. It looks almost the same as the image you pasted. 
無題
無題1

**Comment by yzyray** [comment]
I added an language item `Lizzie.defaultFontName` for setting all component's font,can you try it and see if this pr need any changes.

**Comment by hope366** [comment]
I tried that PR. 
`<html> <span style =" font-family: Yu Gothic UI; ">`
I tried it with a file without this html tag, but all the characters are Yu Gothic UI. It looks like there are no problems so far.
I shouldn't spend a lot of time adding html tags and instead ask you for advice. 😅

**Comment by yzyray** [comment]
I have not aware of using html label to change fonts,so In my mind the only way is use a font name to cover all things you want to change font😂

**Comment by hope366** [comment]
https://github.com/yzyray/lizzieyzy/commit/c00fa05f1008315d8c7141b59a25e88637bb69c9
It turns out that not all items are in the Yu Gothic UI even after using this. It doesn't seem to work mainly in dialog windows. 
As an example, paste the image of "Settings-> Config-> UI". The top is using the html tag, and the bottom is using https://github.com/yzyray/lizzieyzy/commit/c00fa05f1008315d8c7141b59a25e88637bb69c9. 
無題
無題1

**Comment by yzyray** [comment]
It seems can not change Tabbed pane's font through this way,added a process to handle the issue,should be fine now.

**Comment by hope366** [comment]
https://github.com/yzyray/lizzieyzy/commit/1e4628426ee8dd5b416fe161b45559603bdbaa68
I tried this. With this change, the window with a lot of information displayed in "Settings-> Config" is now the Yu Gothic UI. 
However, not all items are in the Yu Gothic UI yet. Observe carefully and present areas that are not yet in the Yu Gothic UI. 
Top right of Hawkeye 
無題
lower left 
無題1
lower left 
無題2
The bottom of the "Game" pull-down menu on the top menu 
無題3

In addition to these, the window related to the sharing function and the window related to the synchronization function are not in the Yu Gothic UI.

**Comment by yzyray** [comment]
Missing all popup menus....Should be fixed now

**Comment by hope366** [comment]
I was able to confirm that the relevant part is the Yu Gothic UI. Thank you.

**Pull request closed without merging**
